### PR TITLE
Handling README.md correctly

### PR DESCRIPTION
**Pull request by drikin**
Gitbook generates index.html from README.md 
It needs to handle it otherwise missing URL link

### CODE REVIEW

**Comment by drikin** [comment]
@jwarby this is fix for https://github.com/jwarby/gitbook-plugin-recently-updated/issues/3
Can you review it?

**Comment by drikin** [comment]
@jwarby sorry for rushing but what do you think?

**Comment by jwarby** [comment]
Hi, I haven't had a chance to look at this yet sorry.

What is the scenario that this fix applies to?  Is it when the main `README.md` file gets updated and it tries to generate a link for it?

**Comment by drikin** [comment]
@jwarby No, it's not only main README.md, gitbook rename any README.md file to index.html.
if somebody modify main, sub or any README.md, and your plugin list it as recently updated, the link is broken. That's why this is required.

**Comment by jwarby** [comment]
Ah I see, thanks for the explanation.

I had a look at the docs to see if there was a better way to do this (I was wary of the original string replacements when I first published this module), and there's actually a `toURL()` function which I somehow missed: https://toolchain.gitbook.com/plugins/api.html#output-instance.

I've had a go at implementing a fix using that instead: https://github.com/jwarby/gitbook-plugin-recently-updated/tree/fix/3-broken-readme-links.

Would you mind trying out that branch for me and letting me know if it fixes the issues you're having?  It seemed good to me but since you're the original reporter I thought it'd be worth you trying it out too.

**Comment by drikin** [comment]
let me try it

**Comment by drikin** [comment]
@jwarby it looks great and much elegant solution than mine.
I tried your branch then worked really well!
Please ship it!! ;-)

**Comment by jwarby** [comment]
@drikin Thanks for testing the fix! Will create a new release with it tomorrow and let you know on here!

**Comment by jwarby** [comment]
Sorry I didn't get around to doing a new release yesterday - just published `v1.0.4` now!  Thanks again.

**Comment by drikin** [comment]
thx a lot!!!

**Pull request closed without merging**
