### PR TITLE
add undefined check for article.path

### PR DESCRIPTION
**Pull request by drikin**
I noticed sometime or some environment, the article.path will return Undefined.
I just checked if its Undefined or not to avoid build break.

Can you do something like this check?
and Bump the version to npm?

### CODE REVIEW

**Comment by drikin** [comment]
@jwarby can you review it?

**Comment by jwarby** [comment]
I'm just wondering why `article.path` would ever be `undefined`?  Just worried that this fix would be a workaround which hides a bigger issue... In what circumstances/environment/etc are you getting `undefined` values?

**Comment by drikin** [comment]
I'm using Gitbook on Ubuntu 18.04 via Windows 10 (1809) WSL.
I'm also wondering why it's undefined in my local environment.
I know what you mean, let me dig into more it.

**Comment by drikin** [comment]
@jwarby sorry for taking a while.
I revisit to investigate this issue.
I found the root of cause reason which is external link in SUMMARY.md
(please reference https://docs.gitbook.com/content-editing/pages-structure#adding-links )

When I put external link in side bar, Gitbook still includes these into article object with url:undefined
I think my patch does make sense to ignore these link object.
(not workaround)

What do you think?

**Comment by jwarby** [comment]
Cool, thanks for verifying. Will push a new release out now.

Thanks again!

**Comment by jwarby** [comment]
`v1.0.2` has been published on NPM now.

**Comment by drikin** [comment]
@jwarby thx for your update!!!

**Pull request merged**
